---
# ------------------------- Service ------------------------- #
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  ports:
  - port: 8888
    name: echo
  selector:
    app: echo

---
# for versions before 1.8.0 use apps/v1beta1
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: echo
  namespace: default
  labels:
    app: echo
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: echo
  template:
    metadata:
      labels:          # required selector
        app: echo
    spec:
      serviceAccount: echo
      containers:
      - name: echo
        image: davidwalter/echo:latest
        imagePullPolicy: Always
        args:
        - "/echo"
        ports:
        - name: echo
          containerPort: 8888
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: echo
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch", "update", "patch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: echo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: echo
subjects:
- kind: ServiceAccount
  name: echo
  namespace: default

# local variables:
# mode: yaml
# end:
